// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlu8Gx2Di7NmwK8ijBOcMo3fWdVplRWZI',
    appId: '1:198264755668:android:40c7fd8415ed130a12f241',
    messagingSenderId: '198264755668',
    projectId: 'nobese-f836f',
    storageBucket: 'nobese-f836f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1WugfQWLV88KHEbJWyQNo9Ic5FpSE4rA',
    appId: '1:198264755668:ios:62641487b224de7a12f241',
    messagingSenderId: '198264755668',
    projectId: 'nobese-f836f',
    storageBucket: 'nobese-f836f.firebasestorage.app',
    androidClientId: '198264755668-7v0v6037pfskq8lmuf0jr34q7gl02svi.apps.googleusercontent.com',
    iosClientId: '198264755668-uvn1lj24r1aah3rg379vtqcfce1ahuuc.apps.googleusercontent.com',
    iosBundleId: 'com.nobese.ahc',
  );

}